name: "Feature Request"
description: "Request a feature you would like added to AE."
labels: ["ype: Feature Request"]
body:
  - type: markdown
    attributes:
      value: |
          Check whether it has already been requested or added.
               You can search the issue tracker to see if what you want has already 
               been requested and/or added to the plugin.
          2.  Only put ONE feature request per issue. This helps us keep track of things.
          3.  Fully fill out the template.
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature
      description: Describe the feature in as much detail as you can.
    validations:
      required: true

